[phases.setup]
nixPkgs = ["nodejs", "openssl", "openssl.dev"]

[phases.install]
cmds = [
  "npm ci --include=dev --no-optional"
]

[phases.build]
cmds = [
  "npm run railway-build",
  "npx prisma generate"
]

[start]
cmd = "npm start"
