#!/bin/bash
# Script to help configure email on production server

echo "📧 Email Configuration Setup for Abcotronics ERP"
echo "=================================================="
echo ""
echo "You need to configure ONE of the following options:"
echo ""
echo "OPTION 1: SendGrid (Recommended)"
echo "---------------------------------"
echo "Add to /var/www/abcotronics-erp/.env:"
echo ""
echo "SENDGRID_API_KEY=SG.your_api_key_here"
echo "EMAIL_FROM=garethm@abcotronics.co.za"
echo ""
echo "OPTION 2: SMTP (Gmail or other)"
echo "---------------------------------"
echo "Add to /var/www/abcotronics-erp/.env:"
echo ""
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=your-email@gmail.com"
echo "SMTP_PASS=your-app-password"
echo "EMAIL_FROM=your-email@gmail.com"
echo ""
echo "After adding these, run:"
echo "  ssh root@165.22.127.196 'cd /var/www/abcotronics-erp && pm2 restart abcotronics-erp'"
echo ""
echo "To check current config:"
echo "  ssh root@165.22.127.196 'cd /var/www/abcotronics-erp && cat .env | grep -E \"SENDGRID|SMTP|EMAIL\"'"
echo ""

