#!/bin/bash
# One-time setup: Create database credentials file on server
# This file should be run ONCE on the server to set up credentials
# The credentials file will NOT be in git

SERVER="root@abcoafrica.co.za"

echo "🔧 Setting up database credentials on server..."
echo "📡 Server: $SERVER"
echo ""

ssh $SERVER << 'SETUP'
set -e

CREDS_FILE="/var/www/abcotronics-erp/.db-credentials.sh"

# Read credentials from environment variables (REQUIRED)
# These must be set when running the script:
#   DB_USERNAME, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME, DB_SSLMODE

if [ -z "$DB_PASSWORD" ]; then
    echo "❌ ERROR: DB_PASSWORD environment variable is required"
    echo ""
    echo "Usage:"
    echo "  DB_PASSWORD='your-password' ./setup-db-credentials-on-server.sh"
    echo ""
    echo "Or set all variables:"
    echo "  DB_USERNAME=doadmin \\"
    echo "  DB_PASSWORD='your-password' \\"
    echo "  DB_HOST='dbaas-db-...' \\"
    echo "  DB_PORT=25060 \\"
    echo "  DB_NAME=defaultdb \\"
    echo "  DB_SSLMODE=require \\"
    echo "  ./setup-db-credentials-on-server.sh"
    exit 1
fi

# Use defaults for other values if not provided
DB_USERNAME="${DB_USERNAME:-doadmin}"
DB_HOST="${DB_HOST:-dbaas-db-6934625-nov-3-backup-nov-3-backup5-do-user-28031752-0.l.db.ondigitalocean.com}"
DB_PORT="${DB_PORT:-25060}"
DB_NAME="${DB_NAME:-defaultdb}"
DB_SSLMODE="${DB_SSLMODE:-require}"

cat > "$CREDS_FILE" << CREDS
#!/bin/bash
# Database credentials - DO NOT COMMIT THIS FILE
# This file is created on the server and contains production database credentials
# Generated by setup-db-credentials-on-server.sh

export DB_USERNAME="$DB_USERNAME"
export DB_PASSWORD="$DB_PASSWORD"
export DB_HOST="$DB_HOST"
export DB_PORT="$DB_PORT"
export DB_NAME="$DB_NAME"
export DB_SSLMODE="$DB_SSLMODE"
CREDS

chmod 600 "$CREDS_FILE"
echo "✅ Database credentials file created at: $CREDS_FILE"
echo "   File permissions set to 600 (read/write for owner only)"
echo ""
echo "📋 Credentials file location: $CREDS_FILE"
echo "   This file is NOT tracked in git and contains production credentials"
SETUP

echo ""
echo "✅ Database credentials setup complete on server!"
echo "   The deployment scripts will now use these credentials automatically"

