-- AlterTable
ALTER TABLE "Client" ADD COLUMN     "address" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "comments" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "contacts" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "followUps" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "industry" TEXT NOT NULL DEFAULT 'Other',
ADD COLUMN     "lastContact" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "notes" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "projectIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "revenue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sites" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "website" TEXT NOT NULL DEFAULT '';
